default: &default
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['LPJK_SURVEY_WEB_DB_NAME'] %>
  username: <%= ENV['LPJK_SURVEY_WEB_DB_USERNAME'] %>
  password: <%= ENV['LPJK_SURVEY_WEB_DB_PASSWORD'] %>
  port: <%= ENV['LPJK_SURVEY_WEB_DB_PORT'] %>
  pool: <%= ENV['LPJK_SURVEY_WEB_DB_CONN_POOL'] ? ENV['LPJK_SURVEY_WEB_DB_CONN_POOL'].to_i : 5 %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
